"""Probe Greenhouse/Lever/Ashby public APIs for each candidate company slug.

Writes companies.yaml with verified entries (ats + slug + live job count).
Run: python scripts/verify_companies.py
"""
import os
import sys
import time

os.environ.setdefault("REQUESTS_CA_BUNDLE", r"C:\Users\ankit\certs\cacert.pem")
import requests  # noqa: E402

# name -> slug guesses to try (usually one)
CANDIDATES = {
    # AI / agentic
    "Anthropic": ["anthropic"],
    "OpenAI": ["openai"],
    "Scale AI": ["scaleai", "scale"],
    "Perplexity": ["perplexity", "perplexityai"],
    "Cohere": ["cohere"],
    "Hugging Face": ["huggingface"],
    "Glean": ["glean", "gleanwork"],
    "Harvey": ["harvey"],
    "Writer": ["writer"],
    "Abridge": ["abridge"],
    # developer tools / platform
    "Vercel": ["vercel"],
    "Linear": ["linear"],
    "Notion": ["notion"],
    "Figma": ["figma"],
    "Replit": ["replit"],
    "Temporal": ["temporaltechnologies", "temporal"],
    "PagerDuty": ["pagerduty"],
    "HashiCorp": ["hashicorp"],
    "GitLab": ["gitlab"],
    "Postman": ["postman"],
    "LaunchDarkly": ["launchdarkly"],
    "Retool": ["retool"],
    # data & analytics
    "Databricks": ["databricks"],
    "dbt Labs": ["dbtlabsinc", "dbtlabs"],
    "Fivetran": ["fivetran"],
    "Hex": ["hex", "hextechnologies"],
    "Sigma Computing": ["sigmacomputing"],
    "Monte Carlo": ["montecarlodata"],
    "Datadog": ["datadog"],
    "Amplitude": ["amplitude"],
    "Airbyte": ["airbyte"],
    "MotherDuck": ["motherduck"],
    # healthcare technology
    "Tempus": ["tempus", "tempuslabs"],
    "Flatiron Health": ["flatironhealth"],
    "Komodo Health": ["komodohealth"],
    "Oscar Health": ["oscar", "oscarhealth"],
    "Hinge Health": ["hingehealth"],
    "Headway": ["headway"],
    "Zocdoc": ["zocdoc"],
    "Cityblock Health": ["cityblockhealth", "cityblock"],
    "Devoted Health": ["devoted", "devotedhealth"],
    "Included Health": ["includedhealth"],
    "Sword Health": ["swordhealth"],
    "Maven Clinic": ["mavenclinic"],
    "Commure": ["commure", "commureathelas"],
    # fintech-adjacent platform (strong PM orgs, enterprise workflows)
    "Stripe": ["stripe"],
    "Ramp": ["ramp"],
    "Plaid": ["plaid"],
    # civic / public interest
    "Code for America": ["codeforamerica"],
    "Nava": ["nava", "navapbc"],
}

S = requests.Session()
S.headers["User-Agent"] = "job-radar-setup/0.1 (personal job search tool)"


def probe(slug: str):
    """Return (ats, job_count) for the first ATS that serves this slug, else None."""
    try:
        r = S.get(f"https://boards-api.greenhouse.io/v1/boards/{slug}/jobs", timeout=12)
        if r.status_code == 200:
            return "greenhouse", len(r.json().get("jobs", []))
    except Exception:
        pass
    try:
        r = S.get(f"https://api.lever.co/v0/postings/{slug}?mode=json", timeout=12)
        if r.status_code == 200 and isinstance(r.json(), list) and r.json():
            return "lever", len(r.json())
    except Exception:
        pass
    try:
        r = S.get(
            f"https://api.ashbyhq.com/posting-api/job-board/{slug}?includeCompensation=true",
            timeout=12,
        )
        if r.status_code == 200:
            return "ashby", len(r.json().get("jobs", []))
    except Exception:
        pass
    return None


def main():
    verified, missed = [], []
    for name, slugs in CANDIDATES.items():
        hit = None
        for slug in slugs:
            res = probe(slug)
            if res:
                hit = (name, res[0], slug, res[1])
                break
            time.sleep(0.2)
        if hit:
            verified.append(hit)
            print(f"OK   {name}: {hit[1]}/{hit[2]} ({hit[3]} jobs)")
        else:
            missed.append(name)
            print(f"MISS {name}")
        sys.stdout.flush()

    lines = [
        "# Tier-1 source registry (BUILDSPEC): one line per company, verified live.",
        f"# Generated by scripts/verify_companies.py — {time.strftime('%Y-%m-%d')}.",
        "# Add a company: append name/ats/slug and rerun this script to verify.",
        "companies:",
    ]
    for name, ats, slug, count in sorted(verified):
        lines.append(f"  - name: {name}")
        lines.append(f"    ats: {ats}")
        lines.append(f"    slug: {slug}")
        lines.append(f"    verified_jobs_at_setup: {count}")
    if missed:
        lines.append("")
        lines.append("# Not found on Greenhouse/Lever/Ashby public APIs (likely Workday/")
        lines.append("# custom/iCIMS — deferred per BUILDSPEC). Candidates to research:")
        for name in sorted(missed):
            lines.append(f"#   {name}")
    out = os.path.join(os.path.dirname(__file__), "..", "companies.yaml")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"\nverified={len(verified)} missed={len(missed)} -> companies.yaml")


if __name__ == "__main__":
    main()
